// data.js
// 漢字ポケット - 問題データ
// 各問題は「回（第◯回）」ごとにグループ化されています。
// sentence 内の {blank} の部分がカタカナ語（漢字に変換する部分）です。

const QUESTIONS = [
  // ========== 第5回（ケンバン〜アテサキ） ==========
  { id: "r5-01", round: 5, kana: "ケンバン",   answer: "鍵盤",   yomi: "けんばん",   sentence: "ピアノの{blank}をたたく。",         hint: "キーボード" },
  { id: "r5-02", round: 5, kana: "カギ",       answer: "鍵",     yomi: "かぎ",       sentence: "事件を解く{blank}を握る。",         hint: "手がかり" },
  { id: "r5-03", round: 5, kana: "ナベリョウリ", answer: "鍋料理", yomi: "なべりょうり", sentence: "{blank}が名物の旅館。",             hint: "なべで材料を煮ながら食べるりょうり" },
  { id: "r5-04", round: 5, kana: "カマクラ",   answer: "鎌倉",   yomi: "かまくら",   sentence: "{blank}時代に勢力をふるう。",       hint: "幕府が置かれた、神奈川県南東部の地名" },
  { id: "r5-05", round: 5, kana: "エサ",       answer: "餌",     yomi: "えさ",       sentence: "金魚に{blank}をやる。",             hint: "食べ物" },
  { id: "r5-06", round: 5, kana: "ガベイ",     answer: "画餅",   yomi: "がべい",     sentence: "彼の計画は{blank}に帰した。",       hint: "役に立たないもの" },
  { id: "r5-07", round: 5, kana: "ゴマ",       answer: "駒",     yomi: "こま",       sentence: "持ち{blank}が多いチーム。",         hint: "いつでも使えるもの・人" },
  { id: "r5-08", round: 5, kana: "ケイガイ",   answer: "形骸",   yomi: "けいがい",   sentence: "制度が{blank}化していく。",         hint: "内容がなくかたちだけのもの" },
  { id: "r5-09", round: 5, kana: "セツナ",     answer: "刹那",   yomi: "せつな",     sentence: "衝突した{blank}、気を失う。",       hint: "瞬間" },
  { id: "r5-10", round: 5, kana: "ハクダツ",   answer: "剥奪",   yomi: "はくだつ",   sentence: "医師の資格を{blank}される。",       hint: "はぎとること" },
  { id: "r5-11", round: 5, kana: "ボッパツ",   answer: "勃発",   yomi: "ぼっぱつ",   sentence: "太平洋戦争が{blank}する。",         hint: "突然始まること" },
  { id: "r5-12", round: 5, kana: "ハガ",       answer: "剥",     yomi: "はが",       sentence: "塗装が{blank}れる。",               hint: "はげ落ちること" },
  { id: "r5-13", round: 5, kana: "シンセキ",   answer: "親戚",   yomi: "しんせき",   sentence: "遠くの{blank}より近くの他人。",     hint: "しんるい" },
  { id: "r5-14", round: 5, kana: "チョウダイ", answer: "頂戴",   yomi: "ちょうだい", sentence: "ありがたく{blank}いたします。",     hint: "いただくこと" },
  { id: "r5-15", round: 5, kana: "タイカン",   answer: "戴冠",   yomi: "たいかん",   sentence: "国王の{blank}式。",                 hint: "かんむりを頭にいただくこと" },
  { id: "r5-16", round: 5, kana: "ダンナ",     answer: "旦那",   yomi: "だんな",     sentence: "店の大{blank}に仕える。",           hint: "男主人" },
  { id: "r5-17", round: 5, kana: "キソン",     answer: "毀損",   yomi: "きそん",     sentence: "名誉{blank}で訴えられる。",         hint: "価値をそこなうこと" },
  { id: "r5-18", round: 5, kana: "ヒゴロ",     answer: "日頃",   yomi: "ひごろ",     sentence: "{blank}の感謝を伝える。",           hint: "ふだん" },
  { id: "r5-19", round: 5, kana: "ヒッス",     answer: "必須",   yomi: "ひっす",     sentence: "合格のための{blank}条件。",         hint: "かならず用いるべきこと" },
  { id: "r5-20", round: 5, kana: "セイトン",   answer: "整頓",   yomi: "せいとん",   sentence: "きれいに{blank}された部屋。",       hint: "きちんと片付けること" },
  { id: "r5-21", round: 5, kana: "ホオ",       answer: "頬",     yomi: "ほお",       sentence: "誰もいない間に{blank}張る。",       hint: "口いっぱい食べること" },
  { id: "r5-22", round: 5, kana: "ガクカンセツ", answer: "顎関節", yomi: "がくかんせつ", sentence: "{blank}を痛める。",                hint: "耳の周辺にある左右一対のかんせつ" },
  { id: "r5-23", round: 5, kana: "アゴ",       answer: "顎",     yomi: "あご",       sentence: "コース前半で{blank}を出した。",     hint: "疲れきること" },
  { id: "r5-24", round: 5, kana: "メイオウセイ", answer: "冥王星", yomi: "めいおうせい", sentence: "{blank}は準惑星とされる。",        hint: "太陽系の天体" },
  { id: "r5-25", round: 5, kana: "アテサキ",   answer: "宛先",   yomi: "あてさき",   sentence: "{blank}不明で戻ってきた。",         hint: "手紙の受け取り手" },

  // ========== 第6回（鉛筆のシン〜ヤセガタ） ==========
  { id: "r6-01", round: 6, kana: "シン",       answer: "芯",     yomi: "しん",       sentence: "鉛筆の{blank}の材料を調べる。",     hint: "中心" },
  { id: "r6-02", round: 6, kana: "カセイ",     answer: "苛政",   yomi: "かせい",     sentence: "{blank}に苦しむ国民。",             hint: "厳しくむごい政治" },
  { id: "r6-03", round: 6, kana: "イシュク",   answer: "萎縮",   yomi: "いしゅく",   sentence: "手足の筋肉が{blank}する。",         hint: "しなびてちぢこまること" },
  { id: "r6-04", round: 6, kana: "ナえる",     answer: "萎える", yomi: "なえる",     sentence: "気持ちが{blank}。",                 hint: "元気がなくなること" },
  { id: "r6-05", round: 6, kana: "カットウ",   answer: "葛藤",   yomi: "かっとう",   sentence: "心の{blank}を描いた文学。",         hint: "もつれ・相反する思いの板ばさみ" },
  { id: "r6-06", round: 6, kana: "ズガイコツ", answer: "頭蓋骨", yomi: "ずがいこつ", sentence: "{blank}に入ったひび。",             hint: "あたまのほね" },
  { id: "r6-07", round: 6, kana: "ヒブタ",     answer: "火蓋",   yomi: "ひぶた",     sentence: "戦いの{blank}が切られる。",         hint: "争いが始まる" },
  { id: "r6-08", round: 6, kana: "サゲスむ",   answer: "蔑む",   yomi: "さげすむ",   sentence: "{blank}ような視線。",               hint: "ばかにすること" },
  { id: "r6-09", round: 6, kana: "インペイ",   answer: "隠蔽",   yomi: "いんぺい",   sentence: "証拠の{blank}を図る。",             hint: "おおいかくすこと" },
  { id: "r6-10", round: 6, kana: "フジ",       answer: "藤",     yomi: "ふじ",       sentence: "{blank}の花が咲く。",               hint: "紫色や白色の蝶形の花" },
  { id: "r6-11", round: 6, kana: "アイイロ",   answer: "藍色",   yomi: "あいいろ",   sentence: "{blank}に染められた布。",           hint: "青みがかった濃い色" },
  { id: "r6-12", round: 6, kana: "サイハイ",   answer: "采配",   yomi: "さいはい",   sentence: "見事な{blank}だった。",             hint: "指図すること" },
  { id: "r6-13", round: 6, kana: "ドウクツ",   answer: "洞窟",   yomi: "どうくつ",   sentence: "壁画が発見された{blank}。",         hint: "ほらあな" },
  { id: "r6-14", round: 6, kana: "ショホウセン", answer: "処方箋", yomi: "しょほうせん", sentence: "医師から{blank}をもらう。",        hint: "投与する薬についての指示書" },
  { id: "r6-15", round: 6, kana: "サイバシ",   answer: "菜箸",   yomi: "さいばし",   sentence: "{blank}は「一膳」と数えない。",     hint: "料理用のはし" },
  { id: "r6-16", round: 6, kana: "トリカゴ",   answer: "鳥籠",   yomi: "とりかご",   sentence: "窓辺に{blank}をつるす。",           hint: "ことりを飼うためのかご" },
  { id: "r6-17", round: 6, kana: "コケツ",     answer: "虎穴",   yomi: "こけつ",     sentence: "{blank}に入るような危険を冒す。",   hint: "とらの巣あな" },
  { id: "r6-18", round: 6, kana: "センチャ",   answer: "煎茶",   yomi: "せんちゃ",   sentence: "{blank}の入れ方にこだわる。",       hint: "りょくちゃ" },
  { id: "r6-19", round: 6, kana: "ホンロウ",   answer: "翻弄",   yomi: "ほんろう",   sentence: "波に{blank}される小舟。",           hint: "もてあそぶこと" },
  { id: "r6-20", round: 6, kana: "エンコン",   answer: "怨恨",   yomi: "えんこん",   sentence: "{blank}による犯行。",               hint: "うらみつらむこと" },
  { id: "r6-21", round: 6, kana: "オンネン",   answer: "怨念",   yomi: "おんねん",   sentence: "死者の{blank}を晴らす。",           hint: "深いうらみ" },
  { id: "r6-22", round: 6, kana: "シイ",       answer: "恣意",   yomi: "しい",       sentence: "{blank}的な判断にすぎない。",       hint: "思いつくまま" },
  { id: "r6-23", round: 6, kana: "コンセキ",   answer: "痕跡",   yomi: "こんせき",   sentence: "何とか{blank}をとどめる。",         hint: "あとかた" },
  { id: "r6-24", round: 6, kana: "ヤセ",       answer: "痩せ",   yomi: "やせ",       sentence: "{blank}た土地でもよく育つ。",       hint: "養分が少ないこと" },

  // ========== 第7回（ソジョウ〜ソウソフ） ==========
  { id: "r7-01", round: 7, kana: "カイヨウ",   answer: "潰瘍",   yomi: "かいよう",   sentence: "胃に{blank}ができたようだ。",       hint: "傷ついて分かれた状態" },
  { id: "r7-02", round: 7, kana: "メジリ",     answer: "目尻",   yomi: "めじり",     sentence: "{blank}にしわを寄せて笑う。",       hint: "目の耳側の端" },
  { id: "r7-03", round: 7, kana: "ソジョウ",   answer: "遡上",   yomi: "そじょう",   sentence: "鮎が川を{blank}する。",             hint: "流れをさかのぼること" },
  { id: "r7-04", round: 7, kana: "サカノボる", answer: "遡る",   yomi: "さかのぼる", sentence: "十年前まで記憶を{blank}。",         hint: "もどること" },
  { id: "r7-05", round: 7, kana: "ケンソン",   answer: "謙遜",   yomi: "けんそん",   sentence: "{blank}して何も言わない。",         hint: "ひかえめにふるまうこと" },
  { id: "r7-06", round: 7, kana: "メンルイ",   answer: "麺類",   yomi: "めんるい",   sentence: "小麦粉を使った{blank}。",           hint: "メンの総称" },
  { id: "r7-07", round: 7, kana: "コウバイ",   answer: "勾配",   yomi: "こうばい",   sentence: "{blank}の急な坂をのぼる。",         hint: "傾斜の度合" },
  { id: "r7-08", round: 7, kana: "ニオい",     answer: "匂い",   yomi: "におい",     sentence: "生活の{blank}を感じない。",         hint: "それらしい感じ" },
  { id: "r7-09", round: 7, kana: "クラヤミ",   answer: "暗闇",   yomi: "くらやみ",   sentence: "山は{blank}に包まれていた。",       hint: "光がなくくらい状態" },
  { id: "r7-10", round: 7, kana: "クシザし",   answer: "串刺し", yomi: "くしざし",   sentence: "団子の{blank}を頬張る。",           hint: "物をくしでさし通すこと" },
  { id: "r7-11", round: 7, kana: "イノチゴい", answer: "命乞い", yomi: "いのちごい", sentence: "{blank}を聞き入れる。",             hint: "いのちを助けるよう頼むこと" },
  { id: "r7-12", round: 7, kana: "テンドン",   answer: "天丼",   yomi: "てんどん",   sentence: "{blank}を三人前注文する。",         hint: "てんぷらの乗ったどんぶり" },
  { id: "r7-13", round: 7, kana: "フロ",       answer: "風呂",   yomi: "ふろ",       sentence: "ひと{blank}浴びる。",               hint: "入浴" },
  { id: "r7-14", round: 7, kana: "ヨウサイ",   answer: "要塞",   yomi: "ようさい",   sentence: "自然の{blank}に囲まれた地。",       hint: "敵を防ぐための地形" },
  { id: "r7-15", round: 7, kana: "ヘイソク",   answer: "閉塞",   yomi: "へいそく",   sentence: "{blank}状況を打破する。",           hint: "とざされてふさがれること" },
  { id: "r7-16", round: 7, kana: "ソウカイ",   answer: "爽快",   yomi: "そうかい",   sentence: "自然に囲まれて{blank}だ。",         hint: "すがすがしい様子" },
  { id: "r7-17", round: 7, kana: "ダンガイ",   answer: "断崖",   yomi: "だんがい",   sentence: "{blank}絶壁の上に立つ。",           hint: "切り立ったがけ" },
  { id: "r7-18", round: 7, kana: "ガケ",       answer: "崖",     yomi: "がけ",       sentence: "{blank}崩れの対策を行う。",         hint: "山や岸などの険しく切り立った所" },
  { id: "r7-19", round: 7, kana: "スナアラシ", answer: "砂嵐",   yomi: "すなあらし", sentence: "{blank}の中から救出する。",         hint: "すなを舞い上げる激しい風" },
  { id: "r7-20", round: 7, kana: "ゾウキン",   answer: "雑巾",   yomi: "ぞうきん",   sentence: "掃除は{blank}がけが一番。",         hint: "汚れをふき取るための布" },
  { id: "r7-21", round: 7, kana: "ゴイ",       answer: "語彙",   yomi: "ごい",       sentence: "{blank}の豊富な人。",               hint: "ある範囲のことばの集まり" },
  { id: "r7-22", round: 7, kana: "ケンポウ",   answer: "拳法",   yomi: "けんぽう",   sentence: "{blank}を護身用に習う。",           hint: "こぶしを用いる中国伝来の武術" },
  { id: "r7-23", round: 7, kana: "シンシ",     answer: "真摯",   yomi: "しんし",     sentence: "{blank}な態度に好感をもつ。",       hint: "まじめでひたむきな様子" },
  { id: "r7-24", round: 7, kana: "ハンテン",   answer: "斑点",   yomi: "はんてん",   sentence: "赤い{blank}が見られる。",           hint: "まだらに散ったてん" },
  { id: "r7-25", round: 7, kana: "ガンタン",   answer: "元旦",   yomi: "がんたん",   sentence: "一年の計は{blank}にあり。",         hint: "がんじつの朝" },
  { id: "r7-26", round: 7, kana: "ソウソフ",   answer: "曽祖父", yomi: "そうそふ",   sentence: "{blank}の代から営む。",             hint: "ひいおじいさん" },

  // ========== 第8回（サンロク〜キレツ） ==========
  { id: "r8-01", round: 8, kana: "サンロク",   answer: "山麓",   yomi: "さんろく",   sentence: "富士{blank}の自然を撮る。",         hint: "やますそ" },
  { id: "r8-02", round: 8, kana: "ツメアト",   answer: "爪痕",   yomi: "つめあと",   sentence: "台風が残した大きな{blank}。",       hint: "災害などが残した無残な被害" },
  { id: "r8-03", round: 8, kana: "ツマサキ",   answer: "爪先",   yomi: "つまさき",   sentence: "{blank}をそろえて立つ。",           hint: "足の指のさき" },
  { id: "r8-04", round: 8, kana: "ゾウゲ",     answer: "象牙",   yomi: "ぞうげ",     sentence: "昔から珍重された{blank}。",         hint: "ゾウのきば" },
  { id: "r8-05", round: 8, kana: "カンペキ",   answer: "完璧",   yomi: "かんぺき",   sentence: "{blank}な演技を見せた選手。",       hint: "かんぜん" },
  { id: "r8-06", round: 8, kana: "ガカイ",     answer: "瓦解",   yomi: "がかい",     sentence: "汚職事件で政権が{blank}する。",     hint: "一部の崩れから全体が崩れること" },
  { id: "r8-07", round: 8, kana: "カワラ",     answer: "瓦",     yomi: "かわら",     sentence: "赤い{blank}の屋根が並ぶ。",         hint: "粘土を一定の形にかためて焼いたもの" },
  { id: "r8-08", round: 8, kana: "イケイ",     answer: "畏敬",   yomi: "いけい",     sentence: "自然への{blank}の念を抱く。",       hint: "おそれうやまうこと" },
  { id: "r8-09", round: 8, kana: "キンキ",     answer: "近畿",   yomi: "きんき",     sentence: "{blank}地方の拠点となる。",         hint: "地区区分の一つ" },
  { id: "r8-10", round: 8, kana: "ミケン",     answer: "眉間",   yomi: "みけん",     sentence: "{blank}のしわ。",                   hint: "まゆとまゆのあいだ" },
  { id: "r8-11", round: 8, kana: "マユネ",     answer: "眉根",   yomi: "まゆね",     sentence: "不快そうに{blank}を寄せる。",       hint: "まゆのねもと" },
  { id: "r8-12", round: 8, kana: "セキズイ",   answer: "脊髄",   yomi: "せきずい",   sentence: "{blank}損傷と診断される。",         hint: "中枢神経の一つ" },
  { id: "r8-13", round: 8, kana: "ジンゾウ",   answer: "腎臓",   yomi: "じんぞう",   sentence: "{blank}を摘出する手術。",           hint: "左右一対の泌尿器官" },
  { id: "r8-14", round: 8, kana: "シュウチ",   answer: "羞恥",   yomi: "しゅうち",   sentence: "{blank}に見舞われる夫婦仲だ。",     hint: "はじらう気持ち" },
  { id: "r8-15", round: 8, kana: "ウラヤむ",   answer: "羨む",   yomi: "うらやむ",   sentence: "人も{blank}夫婦仲だ。",             hint: "そうありたいと思うこと" },
  { id: "r8-16", round: 8, kana: "センボウ",   answer: "羨望",   yomi: "せんぼう",   sentence: "{blank}のまなざし。",               hint: "うらやむこと" },
  { id: "r8-17", round: 8, kana: "イロツヤ",   answer: "色艶",   yomi: "いろつや",   sentence: "肌の{blank}がよい。",               hint: "いろとはり" },
  { id: "r8-18", round: 8, kana: "ハチミツ",   answer: "蜂蜜",   yomi: "はちみつ",   sentence: "{blank}は栄養価が高い。",           hint: "はちがたくわえたみつ" },
  { id: "r8-19", round: 8, kana: "ダッキュウ", answer: "脱臼",   yomi: "だっきゅう", sentence: "{blank}予防のトレーニング。",       hint: "骨の関節が外れること" },
  { id: "r8-20", round: 8, kana: "トンヨク",   answer: "貪欲",   yomi: "どんよく",   sentence: "{blank}に知識を吸収する。",         hint: "非常によく深いようす" },
  { id: "r8-21", round: 8, kana: "シンラツ",   answer: "辛辣",   yomi: "しんらつ",   sentence: "批評は{blank}をきわめた。",         hint: "手厳しいようす" },
  { id: "r8-22", round: 8, kana: "チャガマ",   answer: "茶釜",   yomi: "ちゃがま",   sentence: "{blank}は茶道具の一種だ。",         hint: "さどうで使うお湯をわかすかま" },
  { id: "r8-23", round: 8, kana: "ユウウツ",   answer: "憂鬱",   yomi: "ゆううつ",   sentence: "今後を考えると{blank}だ。",         hint: "気が晴れないこと" },
  { id: "r8-24", round: 8, kana: "カンコクゴ", answer: "韓国語", yomi: "かんこくご", sentence: "{blank}を流ちょうに話す。",         hint: "かんこくで話されている言葉の通称" },
  { id: "r8-25", round: 8, kana: "センバヅル", answer: "千羽鶴", yomi: "せんばづる", sentence: "願いをこめて{blank}を折る。",       hint: "せんばのおりづる" },
  { id: "r8-26", round: 8, kana: "キレツ",     answer: "亀裂",   yomi: "きれつ",     sentence: "二人の間に{blank}が入る。",         hint: "ひび" },
];

// 回のメタ情報
const ROUNDS = [
  { round: 5, label: "第5回" },
  { round: 6, label: "第6回" },
  { round: 7, label: "第7回" },
  { round: 8, label: "第8回" },
];
